<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/e96633bd75.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Days+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo constant('URL'); ?>public/css/adquirencia_new.css">
    <title>CHECKER PPI - autopresentación</title>
</head>
<body>
    <?php require 'views/header.phtml'; ?>
    <script src="<?php echo constant('URL'); ?>js/autopresentacion.js "></script>
</body>
</html>